# Generated by Django 3.2.6 on 2022-04-03 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 3, 20, 2, 31, 71045)),
        ),
    ]
