# Generated by Django 3.2.6 on 2022-03-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(default='media/patients/default.jpg', upload_to='media/patients/'),
        ),
    ]
