# Generated by Django 3.2.6 on 2022-03-31 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 31, 17, 9, 27, 5480)),
        ),
    ]
