

class RESERVATION_STATUS:
    ACCEPTED = 0
    PENDING = 1
    REJECTED = 2
    COMPLETED = 3


RESERVATION_STATUS_CHOICES = [
    (RESERVATION_STATUS.ACCEPTED, 'Accepted'),
    (RESERVATION_STATUS.PENDING, 'Pending'),
    (RESERVATION_STATUS.REJECTED, 'Rejected'),
    (RESERVATION_STATUS.COMPLETED, 'Completed'),
]
