# Generated by Django 3.2.6 on 2022-03-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_duration_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duration',
            new_name='ClinicDuration',
        ),
    ]
