# Generated by Django 3.2.6 on 2022-03-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0001_initial'),
        ('doctor', '0003_rename_duration_clinicduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicduration',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='specialty.specialty'),
        ),
    ]
