# Generated by Django 3.2.6 on 2022-03-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_clinicduration_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicduration',
            options={'verbose_name': 'Clinic Duration', 'verbose_name_plural': 'Durations'},
        ),
    ]
