# Generated by Django 3.2.6 on 2022-03-24 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_clinicduration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 24, 5, 43, 45, 42584)),
        ),
    ]
