# Generated by Django 3.2.6 on 2022-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20220511_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='background_image',
            field=models.ImageField(default='doctors/background/default.png', upload_to='doctors/background.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(default='doctors/avatar/default.png', upload_to='doctors/avatar/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
