# Generated by Django 3.2.6 on 2021-08-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='clinic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reservation', to='clinic.clinic'),
            preserve_default=False,
        ),
    ]
