# Generated by Django 3.2.6 on 2021-08-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('reservation', '0002_reservation_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reservation', to='clinic.clinic'),
        ),
    ]
