# Generated by Django 3.2.6 on 2022-03-31 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 31, 17, 9, 27, 5480)),
        ),
    ]
