# Generated by Django 3.2.6 on 2022-04-03 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20220331_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='app_id',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='channel',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 3, 20, 2, 31, 71045)),
        ),
    ]
